version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

  postgresdb:
    image: postgres:13
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  gate-simulator:
    image: node:18
    working_dir: /app
    volumes:
      - ./gate-simulator:/app
    ports:
      - "9999:9999"
    command: npm start